title: Sarah Jafri # your name (or website title) here
logo: "/images/1637326082538.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Whilst doing my MSc in Healthcare Ethics & Law, I realised my work is based on pre-empting situations before they occur and what implications they will have on people, communities and society at large. I decided to solve problems using data-led solutions. I focus on maximising impact and flag risk-factors in my solutions. My holistic understanding of a dataset enables me to create models which can easily be applied in real life. I love being able to use data analysis to create optimal strategies.
  <br><br>
  Agile PM support. 
  <br><br>
  <a href="https://www.linkedin.com/in/sarah-jafri-ab028922">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
